<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Estados [
    <!ELEMENT Estados (Estado*)>
    <!ATTLIST Estado EstadoId ID #REQUIRED>
    <!ELEMENT Estado (Tipo)>
    <!ELEMENT Tipo (#PCDATA)>
]>
<Estados>
    <Estado EstadoId="1">
        <Tipo>Espera</Tipo>
    </Estado>
    <Estado EstadoId="2">
        <Tipo>Listo para distribuir</Tipo>
    </Estado>
    <Estado EstadoId="3">
        <Tipo>Finalizado</Tipo>
    </Estado>
</Estados>